# node.js 18 on alpine linux
FROM node:18-alpine

# app directory
WORKDIR /app

# install dependencies
COPY package*.json ./
RUN npm install

# add app code
COPY . .

# set backend URL
ARG NEXT_PUBLIC_BACKEND_URL
ENV NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL

# build app
RUN npm run build

# open port 3000
EXPOSE 3000

# launch app
CMD ["npm", "start"]