# python 3.10 base image
FROM python:3.10-slim

# install git
RUN apt-get update && apt-get install -y git

# set up working directory
WORKDIR /app

# install python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# copy application code
COPY . .

# install additional packages
RUN pip install git+https://github.com/MIDORIBIN/langchain-gpt4free.git
RUN pip install -U langchain-community

# install gunicorn server
RUN pip install gunicorn

# open port 5000
EXPOSE 5000

# start the application with gunicorn
CMD ["gunicorn", "-b", "0.0.0.0:5000", "main:app"]