name: Frontend CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  frontend-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clean workspace
        run: git clean -fdx

      - name: Build Docker image
        env:
          NEXT_PUBLIC_BACKEND_URL: "http://k8s-threetie-mainlb-9351bb8505-1714127208.ap-southeast-2.elb.amazonaws.com/api"
        run: |
          cd frontend
          docker system prune -f
          docker container prune -f
          docker build --build-arg NEXT_PUBLIC_BACKEND_URL=${{ env.NEXT_PUBLIC_BACKEND_URL }} -t rsduran/frontend:${{ github.run_number }} -f Dockerfile.frontend .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image to DockerHub
        run: docker push rsduran/frontend:${{ github.run_number }}

      - name: Update Kubernetes deployment
        run: |
          cd Kubernetes-Manifests/Frontend
          git config user.email "reineirsamonteduran@gmail.com"
          git config user.name "rsduran"
          # Use grep to find the current image tag and update it
          imageTag=$(grep -oP '(?<=frontend:)[^ ]+' deployment.yaml)
          sed -i "s|rsduran/frontend:${imageTag}|rsduran/frontend:${{ github.run_number }}|" deployment.yaml
          git add deployment.yaml
          git diff --quiet && git diff --staged --quiet || git commit -m "Update frontend image to version ${{ github.run_number }}"

      - name: Pull latest changes
        run: |
          git pull --rebase origin main

      - name: Push changes if there are any
        if: success()
        run: |
          git push https://rsduran:${{ secrets.GITHUB_TOKEN }}@github.com/rsduran/quiz-app.git || echo "No changes to push"
